### ISSUE TITLE
Redis image is gone

### ISSUE THREAD

**Issue by jpopelka** [packit-service/deployment#48]
[registry.fedoraproject.org/f28/redis](https://github.com/packit-service/deployment/blob/master/openshift/redis.yml#L41)

**Comment by csomh** [comment]
@cverna on #fedora-containers told that there was a cleanup on registry.fedoraproject.org in order to get back some storage, and EOL images were pruned.

@hhorak is (was?) the owner of [container/redis](https://src.fedoraproject.org/container/redis), but I'm not sure if he still wants to maintain it.

In the mean time I was able to build the image from the f30 branch, after updating the base image to Fedora 31, and pushed to `quay.io/hcsomort/redis`.

Deployment in a local cluster worked, though more testing would be needed.

@TomasTomecek @jpopelka any ideas how we should proceed?

**Comment by jpopelka** [comment]
> pushed to `quay.io/hcsomort/redis`

Perfect.
We also have [our org @ Docker Hub](https://hub.docker.com/orgs/usercont/repositories), but we might eventually move to Quay, so I don't mind where the image is.

**Comment by hhorak** [comment]
We (the RHSCL container team) still want to maintain redis container in Fedora, although I admit we haven't done the best work recently. I've resurrected that image and just submitted an update to the bodhi:

https://bodhi.fedoraproject.org/updates/FEDORA-CONTAINER-2020-70c733b39a
